### PR TITLE
Add `run_brakeman_scanner` command to danger

### PR DESCRIPTION
**Pull request by BuonOmo**
Now `klaxit.common` has brakeman power. This will work only if a rails app is detected (if there is an `app/` folder).

You can see a preview in klaxit/klaxit-matcher#371.

### CODE REVIEW

**Comment by BuonOmo** [comment]
[(3) [SECU] Implémentation de l'audit automatique - suite](https://trello.com/c/wqOk18pB/851-3-secu-impl%C3%A9mentation-de-laudit-automatique-suite)

**Comment by pyrsmk** [comment]
> You can see a preview in klaxit/klaxit-matcher#371.

In fact, people outside the Klaxit team cannot.

**Comment by BuonOmo** [comment]
@pyrsmk that is why **you** are assigned to this PR ;)

**Comment by pyrsmk** [comment]
@BuonOmo : how can I test it locally ?

Otherwise, it looks good to me but I would like a review from someone who knows danger and gemspec files. @hugobarthelemy ?

**Comment by BuonOmo** [comment]
> @BuonOmo : how can I test it locally ?

Impossible, danger works againts PR. However you can run it against a PR of you choice with `danger pr <pr-url>`, This will run a project's current dangerfile for the metadata of a given pull request. That is the tool I used to test this againts klaxit/klaxit-matcher

**Pull request merged**
